
stages:
  load_data:
    cmd: python src/stage1.py --config=config/config.yaml
    deps:
      - src/stage1.py
      - src/utils/all_utils.py
      - config/config.yaml

    outs:
      - data/cat
      - data/dog


  prepare_base_model:
    cmd: python src/stage2.py --config=config/config.yaml --params=params.yaml
    deps:
      - src/stage2.py
      - src/utils/all_utils.py
      - config/config.yaml
      - src/utils/models.py

    params:
        - IMAGE_SIZE
        - LEARNING_RATE

    outs:
      - artifacts/base_model/updated_VGG16_base_model.h5
      - artifacts/base_model/VGG16_base_model.h5

  